async(page)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const go=async(path,scenario='default',role='super_admin')=>{await page.goto(`http://127.0.0.1:3008/?role=${role}&managementScenario=${scenario}#/management/${path}`);await page.reload();await page.getByRole('heading',{name:{usage:'调用统计',monitor:'执行监控',users:'用户与角色',skills:'Skill 管理',settings:'系统配置'}[path],exact:true}).waitFor();};
 const select=async(name,label)=>{await page.getByRole('combobox',{name,exact:true}).focus();await page.getByRole('combobox',{name,exact:true}).press('ArrowDown');await page.getByRole('option',{name:label,exact:true}).click();};
 await go('usage');await page.getByText('首次 3 / 单张返工 0 / 整套返工 0',{exact:false}).waitFor();await page.getByRole('button',{name:'展开明细'}).click();await page.getByRole('dialog',{name:'调用明细'}).getByText('未提供',{exact:true}).first().waitFor();await page.keyboard.press('Escape');
 await go('usage','empty');await page.getByText('此范围暂无执行记录').waitFor();await page.getByText('无数据',{exact:true}).first().waitFor();
 await go('usage','list-error');await page.getByText('模拟请求失败，请重试',{exact:true}).waitFor();await page.getByRole('button',{name:'重试加载'}).click();await page.getByText('首次 3 / 单张返工 0',{exact:false}).waitFor();
 await go('monitor','idle');await page.getByText('空闲',{exact:true}).first().waitFor();await go('monitor','unknown');await page.getByText('健康检查已过期或尚未提供',{exact:false}).waitFor();await go('monitor','unavailable');await page.getByText('MinIO 当前不可达',{exact:false}).waitFor();
 await go('monitor','default','design_manager');await page.getByText('总体服务',{exact:true}).waitFor();if(await page.getByRole('heading',{name:'执行环境'}).count())throw Error('主管泄漏环境详情');
 await go('users','save-error');const pending=page.getByRole('row').filter({hasText:'新成员'});await pending.getByRole('button',{name:'分配角色 / 状态'}).click();await select('账号状态','启用');await page.getByRole('button',{name:'保存授权'}).click();await page.getByText('启用账号前请选择业务角色').waitFor();await select('业务角色','设计人员');await page.getByRole('button',{name:'保存授权'}).click();await page.getByText('模拟请求失败，请重试',{exact:true}).waitFor();await page.getByRole('button',{name:'保存授权'}).click();await page.getByRole('dialog',{name:'成员授权'}).waitFor({state:'hidden'});await pending.getByText('设计人员',{exact:true}).waitFor();await pending.getByText('启用',{exact:true}).waitFor();
 await pending.getByRole('button',{name:'分配角色 / 状态'}).click();await select('账号状态','禁用');await page.getByRole('button',{name:'保存授权'}).click();await page.getByRole('dialog',{name:'成员授权'}).waitFor({state:'hidden'});await pending.getByText('禁用',{exact:true}).waitFor();
 await go('settings','save-error');await page.getByLabel('执行并发',{exact:true}).fill('3');await page.getByRole('button',{name:'保存配置'}).click();await page.getByText('模拟请求失败，请重试',{exact:true}).waitFor();if(await page.getByLabel('执行并发',{exact:true}).inputValue()!=='3')throw Error('保存失败丢输入');await page.getByRole('button',{name:'保存配置'}).click();await page.getByText('执行与上传 · 配置 v2').waitFor();await page.getByRole('cell',{name:'执行并发',exact:true}).waitFor();await page.getByLabel('HTTPS 回调域名').fill('http://unsafe.example.com');await page.getByRole('button',{name:'保存配置'}).click();await page.getByText('回调域名需为 HTTPS 域名',{exact:false}).waitFor();
 await go('skills','install-error');await page.getByRole('button',{name:'上传 Skill 包'}).click();await page.getByLabel('Skill 版本号').fill('2.0.0');await page.getByLabel('Skill ZIP 包').setInputFiles('output/playwright/phase4-skill.zip');await page.getByRole('button',{name:'上传版本',exact:true}).click();await page.getByRole('dialog',{name:'上传 Skill 版本'}).waitFor({state:'hidden'});const skill=page.getByRole('row').filter({hasText:'phase4-skill.zip'});await skill.getByRole('button',{name:'安装版本',exact:true}).click();await skill.getByText('安装失败',{exact:true}).waitFor();if(await page.getByText('可用',{exact:true}).count()!==3)throw Error('失败损坏旧版本');await skill.getByRole('button',{name:'重试安装'}).click();await skill.getByText('可用',{exact:true}).waitFor();await skill.getByRole('button',{name:'停用',exact:true}).click();await page.getByRole('button',{name:'确认停用'}).click();await skill.getByText('已停用',{exact:true}).waitFor();await skill.getByRole('button',{name:'设为可用'}).click();await skill.getByText('可用',{exact:true}).waitFor();
 if(errors.length)throw Error(errors.join('\n'));return 'PASS 管理统计、监控、用户授权、配置故障与恢复';
}
