async (page) => {
  await page.goto('http://127.0.0.1:3008/?scenario=save-error#/templates/index');
  await page.reload();
  await page.getByRole('button',{name:'新建模板',exact:true}).click();
  let dialog=page.getByRole('dialog',{name:'新建套图模板',exact:true});
  await dialog.getByRole('button',{name:'保存模板',exact:true}).click();
  await page.getByText('请填写模板名称并添加图片',{exact:true}).waitFor();
  await dialog.getByRole('textbox',{name:'*模板名称',exact:true}).fill('Phase2 排序模板');
  await dialog.getByRole('button',{name:'使用示例套图',exact:true}).click();
  const first=await dialog.locator('.picture-meta span').first().textContent();
  await dialog.getByRole('button',{name:'后移图片 1',exact:true}).click();
  if(await dialog.locator('.picture-meta span').nth(1).textContent()!==first) throw new Error('图片未排序');
  await dialog.getByRole('button',{name:'保存模板',exact:true}).click();
  await dialog.getByRole('alert').filter({hasText:'模拟服务本次接收失败'}).waitFor();
  if(await dialog.getByRole('textbox',{name:'*模板名称',exact:true}).inputValue()!=='Phase2 排序模板') throw new Error('保存失败丢失输入');
  await dialog.getByRole('button',{name:'保存模板',exact:true}).click();
  await dialog.waitFor({state:'hidden'});
  let card=page.locator('.hx-library-card').filter({hasText:'Phase2 排序模板'});
  await card.getByText('版本 v1',{exact:false}).waitFor();
  await card.getByRole('button',{name:'配置模板',exact:true}).click();
  dialog=page.getByRole('dialog',{name:'配置模板',exact:true});
  await dialog.locator('.picture-meta span').nth(1).waitFor();
  if(await dialog.locator('.picture-meta span').nth(1).textContent()!==first) throw new Error('保存后顺序未保留');
  await dialog.getByRole('textbox',{name:'*模板名称',exact:true}).fill('Phase2 排序模板 v2');
  await dialog.getByRole('button',{name:'保存模板',exact:true}).click();
  await dialog.waitFor({state:'hidden'});
  card=page.locator('.hx-library-card').filter({hasText:'Phase2 排序模板 v2'});
  await card.getByText('版本 v2',{exact:false}).waitFor();
  await card.getByRole('button',{name:'使用模板',exact:true}).click();
  await page.getByRole('heading',{name:'替换壁纸',exact:true}).waitFor();
  await page.getByText('Phase2 排序模板 v2 · v2',{exact:true}).waitFor();
  await page.getByRole('menuitem',{name:'模板库',exact:true}).click();
  await page.getByRole('textbox',{name:'搜索模板名称'}).fill('Phase2 排序模板 v2');
  card=page.locator('.hx-library-card').filter({hasText:'Phase2 排序模板 v2'});
  await card.getByRole('button',{name:'删除模板',exact:true}).click();
  let confirm=page.getByRole('dialog',{name:'删除模板',exact:true});
  await confirm.getByRole('button',{name:'取消',exact:true}).click();
  await card.waitFor();
  await card.getByRole('button',{name:'删除模板',exact:true}).click();
  await confirm.getByRole('button',{name:'确认删除',exact:true}).click();
  await page.getByText('暂无匹配模板，可新建或清除筛选',{exact:true}).waitFor();
  await page.goto('http://127.0.0.1:3008/?scenario=no-skills#/templates/index');
  await page.getByRole('button',{name:'新建模板',exact:true}).click();
  dialog=page.getByRole('dialog',{name:'新建套图模板',exact:true});
  await dialog.getByRole('textbox',{name:'*模板名称',exact:true}).fill('无 Skill 草稿');
  await dialog.getByRole('button',{name:'使用示例套图',exact:true}).click();
  await dialog.getByRole('button',{name:'保存草稿',exact:true}).click();
  await dialog.waitFor({state:'hidden'});
  card=page.locator('.hx-library-card').filter({hasText:'无 Skill 草稿'});
  if(!await card.getByRole('button',{name:'使用模板',exact:true}).isDisabled()) throw new Error('草稿可以生成');
  await page.goto('http://127.0.0.1:3008/?scenario=no-skills#/image-processing/text');
  await page.getByRole('heading',{name:'替换文字',exact:true}).waitFor();
  await page.getByText('暂无可用 Skill',{exact:true}).waitFor();
  if(!await page.getByRole('button',{name:'提交生成任务'}).isDisabled()) throw new Error('无 Skill 可生成');
  await page.goto('http://127.0.0.1:3008/?scenario=list-error#/templates/index');
  await page.getByRole('button',{name:'重试加载',exact:true}).click();
  await page.locator('.hx-library-card').first().waitFor();
  await page.screenshot({path:'output/playwright/phase2-templates.png',fullPage:true});
  return 'PASS 模板必填/排序持久/保存失败保留/版本递增/使用深链接/删除取消确认/草稿不可生成/无Skill文字阻断/列表重试';
}
