async(page)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3008/?scenario=revision-error#/tasks/index?task=HX0908-001');
 await page.reload();
 const drawer=page.getByRole('dialog',{name:'秋日山川 · 手机屏幕系列',exact:true});
 await drawer.waitFor();
 await drawer.getByRole('button',{name:'归档到成品库',exact:true}).click();
 await drawer.getByRole('button',{name:'再次归档当前整套',exact:true}).waitFor();
 await drawer.getByRole('button',{name:'修改这张',exact:true}).nth(1).click();
 const feedback=page.getByRole('dialog',{name:'修改第 2 张图片',exact:true});
 if(!await feedback.getByRole('button',{name:'提交修改'}).isDisabled())throw new Error('空意见可提交');
 await feedback.getByRole('textbox').fill('只调整第二张壁纸');
 await feedback.getByRole('button',{name:'提交修改'}).click();
 await feedback.waitFor({state:'hidden'});
 await drawer.getByRole('button',{name:'重试失败范围'}).waitFor();
 if(await drawer.getByText('v1 · 当前版本',{exact:true}).count()!==8)throw new Error('失败未保留旧版');
 if(!await drawer.getByRole('button',{name:'下载整套示例'}).isDisabled())throw new Error('失败仍可整套下载');
 await page.screenshot({path:'output/playwright/phase3-revision-failed.png'});
 await drawer.getByRole('button',{name:'重试失败范围'}).click();
 await drawer.getByText('v2 · 当前版本',{exact:true}).waitFor();
 if(await drawer.getByText('v1 · 当前版本',{exact:true}).count()!==7)throw new Error('单图返工改了其他槽');
 await drawer.getByRole('combobox',{name:'查看图片版本'}).nth(1).focus();
 await drawer.getByRole('combobox',{name:'查看图片版本'}).nth(1).press('ArrowDown');
 await page.getByRole('option',{name:'v1 · 历史版本',exact:true}).click();
 await drawer.getByText('正在查看历史版本，不改变当前结果。',{exact:true}).waitFor();
 const singleEvent=page.waitForEvent('download');
 await drawer.getByRole('button',{name:'下载示例',exact:true}).nth(1).click();
 const single=await singleEvent; if(!single.suggestedFilename().endsWith('.svg'))throw new Error('单图格式错误');
 await single.saveAs('output/playwright/phase3-history.svg');
 const zipEvent=page.waitForEvent('download');
 await drawer.getByRole('button',{name:'下载整套示例'}).click();
 const zip=await zipEvent; if(!zip.suggestedFilename().endsWith('.zip'))throw new Error('整套不是zip');
 await zip.saveAs('output/playwright/phase3-current.zip');
 await drawer.getByRole('button',{name:'归档到成品库',exact:true}).click();
 await drawer.getByRole('button',{name:'再次归档当前整套'}).waitFor();
 await drawer.getByRole('button',{name:'再次归档当前整套'}).click();
 await page.waitForFunction(()=>!document.querySelector('.hx-detail button.is-loading'));
 await drawer.getByRole('button',{name:'关闭此对话框',exact:true}).click();
 await drawer.waitFor({state:'hidden'});
 await page.getByRole('textbox',{name:'搜索任务',exact:true}).fill('HX0908-001');
 const row=page.getByRole('row').filter({hasText:'HX0908-001'});
 await row.getByRole('button',{name:'删除',exact:true}).click();
 let confirm=page.getByRole('dialog',{name:'删除任务',exact:true});
 await confirm.getByRole('button',{name:'取消',exact:true}).click();
 await row.getByRole('button',{name:'删除',exact:true}).click();
 await confirm.getByRole('button',{name:'确认删除',exact:true}).click();
 await page.getByText('暂无匹配任务',{exact:true}).waitFor();
 await page.getByRole('menuitem',{name:'成品库',exact:true}).click();
 await page.getByRole('textbox',{name:'搜索成品名称'}).fill('秋日山川');
 await page.getByText('2 套匹配成品',{exact:true}).waitFor();
 if(await page.locator('.hx-library-card').count()!==2)throw new Error('重复归档或删除任务破坏归档');
 await page.getByRole('button',{name:'查看成品'}).first().click();
 let archived=page.getByRole('dialog',{name:'秋日山川 · 手机屏幕系列',exact:true});
 await archived.getByText('v2',{exact:true}).waitFor();
 if(await archived.getByText('v1',{exact:true}).count()!==7)throw new Error('归档未使用当前整套');
 await archived.getByRole('button',{name:'关闭此对话框',exact:true}).click();
 await page.getByRole('button',{name:'查看成品'}).nth(1).click();
 archived=page.getByRole('dialog',{name:'秋日山川 · 手机屏幕系列',exact:true});
 await archived.getByText('v1',{exact:true}).first().waitFor();
 if(await archived.getByText('v1',{exact:true}).count()!==8)throw new Error('旧归档被覆盖');
 await archived.getByRole('button',{name:'关闭此对话框',exact:true}).click();
 if(errors.length)throw new Error(errors.join(';'));
 return 'PASS 单张失败旧图保留/重试原范围/其余7槽不变/历史v1查看与下载/完整ZIP/当前版本归档幂等/删除确认/旧新归档保留，pageerror=0';
}
