async (page) => {
  const origin = page.url().split('/').slice(0, 3).join('/');
  const errors = [];
  const stable = async () => {
    await page.waitForFunction(() => !Array.from(document.querySelectorAll('.el-loading-mask, .el-message')).some(e => e.getClientRects().length && getComputedStyle(e).visibility !== 'hidden'));
  };
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(origin + '/#/management/skills');
  await page.getByRole('heading', { name: 'Skill 管理', exact: true }).waitFor();
  await page.getByRole('button', { name: '上传 Skill 包', exact: true }).click();
  let dialog = page.getByRole('dialog', { name: '上传 Skill 版本' });
  await dialog.getByRole('textbox', { name: 'Skill 版本号' }).fill('3.0.0');
  await dialog.getByLabel('Skill ZIP 包').setInputFiles('output/playwright/phase7-skill.zip');
  const uploadedResponse = page.waitForResponse(r => r.url().endsWith('/management/skills') && r.request().method() === 'POST');
  await dialog.getByRole('button', { name: '上传版本', exact: true }).click();
  const response = await uploadedResponse;
  if (response.status() !== 201) throw Error('UI上传失败: ' + await response.text());
  const skill = await response.json();
  const row = page.getByRole('row').filter({ hasText: '3.0.0' });
  await row.getByRole('button', { name: '安装版本', exact: true }).click();
  await row.getByText('可用', { exact: true }).waitFor({ timeout: 60000 });
  await page.locator('.el-select').filter({ has: page.getByRole('combobox', { name: '替换壁纸默认 Skill' }) }).click();
  await page.getByRole('option').filter({ hasText: '3.0.0' }).click();
  const defaultsResponse = page.waitForResponse(r => r.url().endsWith('/skills/defaults') && r.request().method() === 'PUT');
  await page.getByRole('button', { name: '保存默认绑定', exact: true }).click();
  if ((await (await defaultsResponse).json()).wallpaper !== skill.id) throw Error('默认未保存');
  await stable();
  await page.screenshot({ path: 'output/playwright/phase7-skills.png', fullPage: true });
  await page.goto(origin + '/#/templates/index');
  await page.getByRole('heading', { name: '模板库', exact: true }).waitFor();
  await page.getByRole('button', { name: '新建模板', exact: true }).click();
  dialog = page.getByRole('dialog', { name: '新建套图模板' });
  await dialog.getByPlaceholder('给这套模板起个容易找到的名字').fill('浏览器版本冻结');
  await dialog.getByText('保存时使用模块默认：', { exact: false }).waitFor();
  await dialog.locator('input[type=file]').setInputFiles(['output/playwright/phase7-pixel.png', 'output/playwright/phase7-pixel.png']);
  await page.waitForFunction(() => document.querySelectorAll('.picture-meta small').length === 2 && Array.from(document.querySelectorAll('.picture-meta small')).every(e => e.textContent === '已接收'));
  const firstResponse = page.waitForResponse(r => r.url().endsWith('/templates') && r.request().method() === 'POST');
  await dialog.getByRole('button', { name: '保存模板', exact: true }).click();
  const firstRaw = await firstResponse;
  if (!firstRaw.ok()) throw Error('创建模板失败: ' + await firstRaw.text());
  const first = await firstRaw.json();
  if (first.skillVersionId !== skill.id || first.skillBinding !== 'module_default' || !first.active) throw Error('默认绑定未冻结');
  const card = page.locator('.hx-library-card').filter({ hasText: '浏览器版本冻结' });
  await card.getByRole('button', { name: '配置模板', exact: true }).click();
  dialog = page.getByRole('dialog', { name: '配置模板' });
  await dialog.getByRole('button', { name: '前移图片 2', exact: true }).click();
  await dialog.getByPlaceholder('可选，补充这套模板的使用说明').fill('保留新顺序');
  let once = true;
  await page.route('**/api/v1/templates/' + first.id, route => {
    if (once && route.request().method() === 'PUT') {
      once = false;
      return route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ code: 'CONFLICT', message: '测试版本冲突，请重新打开' }) });
    }
    return route.continue();
  });
  await dialog.getByRole('button', { name: '保存模板', exact: true }).click();
  await dialog.getByText('测试版本冲突，请重新打开', { exact: true }).waitFor();
  if (await dialog.getByPlaceholder('可选，补充这套模板的使用说明').inputValue() !== '保留新顺序') throw Error('冲突丢失表单');
  const secondResponse = page.waitForResponse(r => r.url().endsWith('/templates/' + first.id) && r.request().method() === 'PUT' && r.ok());
  await dialog.getByRole('button', { name: '保存模板', exact: true }).click();
  const second = await (await secondResponse).json();
  if (second.version !== 2 || second.images[0].fileId !== first.images[1].fileId) throw Error('图片顺序未保存');
  await card.getByRole('button', { name: '历史版本', exact: true }).click();
  const history = page.getByRole('dialog', { name: '模板历史版本' });
  await history.getByText('v2 · 浏览器版本冻结', { exact: true }).waitFor();
  await history.getByText('v1 · 浏览器版本冻结', { exact: true }).click();
  const stored = await (await page.request.get(origin + '/api/v1/templates/' + first.id + '/versions')).json();
  if (stored.length !== 2 || stored[1].images[0].fileId !== first.images[0].fileId) throw Error('旧版本被覆盖');
  await page.setViewportSize({ width: 1024, height: 768 });
  await stable();
  await page.screenshot({ path: 'output/playwright/phase7-history.png', fullPage: true });
  if (await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)) throw Error('历史界面横向溢出');
  await history.getByRole('button', { name: '关闭', exact: true }).click();
  await card.getByRole('button', { name: '使用模板', exact: true }).click();
  await page.getByRole('heading', { name: '替换壁纸', exact: true }).waitFor();
  await page.getByText('正在加载模板…', { exact: true }).waitFor({ state: 'hidden' });
  await page.getByText('加载 Skill…', { exact: true }).waitFor({ state: 'hidden' });
  await stable();
  await page.screenshot({ path: 'output/playwright/phase7-neighbor.png', fullPage: true });
  await page.goto(origin + '/#/templates/index');
  await page.getByRole('heading', { name: '模板库', exact: true }).waitFor();
  await card.getByRole('button', { name: '删除模板', exact: true }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await card.waitFor({ state: 'detached' });
  if ((await page.request.get(origin + '/api/v1/templates/' + first.id)).status() !== 404) throw Error('模板删除未落库');
  if (errors.length) throw Error(errors.join('\n'));
  return 'PHASE7 BROWSER PASS: upload/install/default/template/edit conflict retained/order/history/narrow/delete; pageerrors=0';
}
