const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
import assert from 'node:assert/strict'
const browser=await chromium.launch({headless:true, ...(process.env.BROWSER_EXECUTABLE ? {executablePath:process.env.BROWSER_EXECUTABLE} : {})})
const context=await browser.newContext({viewport:{width:1440,height:1000}})
const page=await context.newPage()
try {
 await page.goto((process.env.DEMO_URL || 'http://127.0.0.1:3010/') + '?role=super_admin#/image-processing/wallpaper')
 await page.getByRole('button',{name:'使用示例素材',exact:true}).click()
 await page.locator('.compact-picture').waitFor()
 assert.equal(await page.locator('.el-upload-dragger').count(),0)
 await page.locator('.image-upload img').first().evaluate(async i=>{await i.decode()})
 await page.locator('.image-upload').screenshot({path:'../../output/compact-upload.png'})
 await page.locator('.image-upload input[type=file]').setInputFiles('public/demo-images/sample-1.jpg')
 await page.waitForFunction(()=>document.querySelectorAll('.compact-picture').length===2)
 await page.locator('.compact-picture .hx-picture').first().click()
 await page.keyboard.press('ArrowRight')
 await page.getByText('本次上传图片 · 2 / 2',{exact:false}).waitFor()
 await page.keyboard.press('Escape')
 await page.getByRole('button',{name:'移除图片 2',exact:true}).click()
 await page.getByRole('button',{name:'移除图片 1',exact:true}).click()
 await page.locator('.el-upload-dragger').waitFor()
 // Empty-state drop must not append the same file twice through bubbling.
 await page.locator('.el-upload-dragger').evaluate(async el=>{
  const bytes=await (await fetch('/demo-images/sample-1.jpg')).blob()
  const data=new DataTransfer();data.items.add(new File([bytes],'drop.jpg',{type:'image/jpeg'}))
  el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}))
 })
 await page.locator('.compact-picture').waitFor()
 await page.waitForTimeout(300)
 assert.equal(await page.locator('.compact-picture').count(),1)
 await page.locator('.image-upload').evaluate(async el=>{
  const bytes=await (await fetch('/demo-images/sample-1.jpg')).blob()
  const data=new DataTransfer();data.items.add(new File([bytes],'append.jpg',{type:'image/jpeg'}))
  el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data}))
 })
 await page.waitForFunction(()=>document.querySelectorAll('.compact-picture').length===2)
 await page.locator('.image-upload input[type=file]').setInputFiles(Array(12).fill('public/demo-images/sample-1.jpg'))
 await page.getByRole('button',{name:'展开全部 · 共 14 张'}).waitFor()
 await page.getByRole('button',{name:'展开全部 · 共 14 张'}).click()
 assert.equal(await page.locator('.compact-picture').count(),14)
 await page.setViewportSize({width:800,height:900})
 await page.getByRole('button',{name:'收起',exact:true}).click()
 assert.ok(await page.locator('.compact-picture').count()<14)
 console.log('PASS: compact after upload, append, preview navigation, remove last, empty drop no duplication, compact drop append, expand/collapse, narrow viewport')
} finally {await context.close();await browser.close()}
