import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const output = path.resolve('../../output/core-ui-fixes-2026-09-22')
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) })
const context = await browser.newContext({ viewport: { width: 1280, height: 900 } })
const page = await context.newPage(), checks = [], errors = []
page.on('pageerror', error => errors.push(error.message))
page.setDefaultTimeout(12000)
const base = process.env.DEMO_URL || 'http://127.0.0.1:3010/'
async function capture(name) {
  await page.waitForLoadState('networkidle')
  await page.waitForFunction(() => [...document.images].filter(i => i.getBoundingClientRect().width > 0).every(i => i.complete && i.naturalWidth > 0))
  await page.screenshot({ path: path.join(output, name + '.png'), animations: 'disabled' })
}
try {
  await page.goto(`${base}?role=super_admin#/tasks/index`)
  const picture = page.locator('.task-picture').first()
  await picture.waitFor()
  await page.waitForFunction(() => document.querySelector('.task-picture img')?.naturalWidth > 0)
  assert.equal(await picture.locator('img').evaluate(e => getComputedStyle(e).objectFit), 'contain')
  await picture.getByRole('button').press('Enter')
  await page.locator('.el-image-viewer__wrapper').waitFor()
  await page.keyboard.press('ArrowRight')
  await page.getByText('2 / 8', { exact: false }).waitFor()
  assert.equal(await page.locator('.hx-detail').isVisible(), false)
  await page.keyboard.press('Escape')
  await picture.getByRole('button').press('Space')
  await page.locator('.el-image-viewer__wrapper').waitFor()
  await page.keyboard.press('Escape')
  checks.push('列表等比缩略图；Enter/Space打开、左右切换、Esc关闭，不触发任务详情')
  await page.evaluate(() => { window.copiedTaskId = ''; Object.defineProperty(navigator.clipboard, 'writeText', { value: async value => { window.copiedTaskId = value }, configurable: true }) })
  const fullId = await page.locator('.task-id small').first().getAttribute('title')
  await page.getByRole('button', { name: `复制任务编号 ${fullId}`, exact: true }).click()
  assert.equal(await page.evaluate(() => window.copiedTaskId), fullId)
  await page.evaluate(() => { Object.defineProperty(navigator.clipboard, 'writeText', { value: async () => { throw new Error('clipboard denied') }, configurable: true }) })
  await page.getByRole('button', { name: `复制任务编号 ${fullId}`, exact: true }).click()
  await page.getByText('任务编号（请手动复制）', { exact: true }).waitFor()
  assert.equal(await page.locator('.el-message-box__message').innerText(), fullId)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByText('我的任务', { exact: true }).click()
  await page.waitForURL(/scope=mine/)
  await page.getByText('暂无匹配任务', { exact: true }).waitFor()
  await page.reload()
  await page.getByRole('radio', { name: '我的任务', exact: true }).waitFor()
  assert.equal(await page.getByRole('radio', { name: '我的任务', exact: true }).isChecked(), true)
  await page.getByText('全员任务', { exact: true }).click()
  await picture.waitFor()
  await capture('task-list-1280')
  checks.push('编号复制完整；我的任务过滤与刷新URL恢复；返回全员任务保留其他人任务')
  await page.goto(`${base}?role=super_admin&scenario=partial-result#/image-processing/text`)
  await page.getByRole('button', { name: '使用示例素材', exact: true }).click()
  await page.getByRole('button', { name: '提交生成任务', exact: true }).click()
  await page.getByRole('button', { name: '重试失败范围', exact: true }).waitFor()
  await page.getByText('本轮 2 张 · 成功 1 张 · 失败 1 张', { exact: true }).waitFor()
  assert.equal(await page.locator('.hx-detail .el-progress').count(), 0)
  assert.match(await page.locator('.hx-detail').innerText(), /重试范围：整套 2 张/)
  await capture('partial-failure-summary')
  await page.getByRole('button', { name: '重试失败范围', exact: true }).click()
  await page.waitForFunction(() => [...document.querySelectorAll('button')].some(b => b.textContent.includes('归档到成品库') && !b.disabled))
  checks.push('部分失败显示真实本轮1成功1失败、明确整套重试范围，重试恢复')
  assert.deepEqual(errors, [])
  await writeFile(path.join(output, 'task-interactions-checks.json'), JSON.stringify({ passed: true, checks, errors }, null, 2))
  console.log(JSON.stringify({ passed: true, checks }))
} catch (error) { await capture('task-interactions-failure').catch(() => {}); console.error(page.url()); throw error }
finally { await context.close(); await browser.close() }
