import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const output = path.resolve('../../output/core-ui-fixes-2026-09-22')
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) })
const context = await browser.newContext({ viewport: { width: 1280, height: 900 } })
const page = await context.newPage(), checks = []
try {
  await page.goto(`${process.env.DEMO_URL || 'http://127.0.0.1:3010/'}?role=super_admin#/image-processing/wallpaper`)
  await page.getByRole('button', { name: '更换模板', exact: true }).click()
  const cards = page.locator('.hx-template-option')
  assert.ok(await cards.count() >= 2)
  for (let i = 0; i < 2; i++) {
    const box = await cards.nth(i).boundingBox()
    assert.ok(box.y >= 0 && box.y + box.height <= 900, `模板 ${i + 1} 完整位于首屏`)
    assert.match(await cards.nth(i).locator('.hx-picker-identity').innerText(), /张 · v/)
    assert.equal(await cards.nth(i).locator('img').first().evaluate(el => getComputedStyle(el).objectFit), 'contain')
  }
  await page.waitForLoadState('networkidle')
  await page.waitForFunction(() => [...document.images].filter(i => i.getBoundingClientRect().width > 0).every(i => i.complete && i.naturalWidth > 0))
  await page.screenshot({ path: path.join(output, 'template-picker-1280.png') })
  await cards.first().locator('.hx-picture').first().click()
  await page.keyboard.press('ArrowRight')
  await page.getByText('2 / 8', { exact: false }).waitFor()
  await page.keyboard.press('Escape')
  await cards.first().locator('.hx-picker-identity').getByText('✓ 当前使用', { exact: true }).waitFor()
  await page.getByRole('button', { name: '取消更换', exact: true }).click()
  await page.getByRole('button', { name: '更换模板', exact: true }).click()
  const newName = await cards.nth(1).locator('.hx-picker-identity strong').innerText()
  await cards.nth(1).getByRole('button', { name: '使用此模板' }).click()
  assert.equal(await page.locator('.hx-selected-template strong').innerText(), newName)
  checks.push('1280×900 两套卡片身份及操作完整可见；等比预览、左右切图、取消及选择有效')
  await page.getByRole('button', { name: '使用示例素材', exact: true }).click()
  await page.getByRole('textbox', { name: '任务名称', exact: true }).fill('单图对照隔离测试')
  await page.getByRole('button', { name: '提交生成任务', exact: true }).click()
  await page.getByRole('button', { name: '修改这张', exact: true }).first().click()
  await page.getByLabel('修改意见', { exact: true }).fill('意见须在原图放大后完整保留')
  const base = page.locator('.revision-base'), editor = page.locator('.revision-editor')
  await page.waitForFunction(() => {
    let el = document.querySelector('.revision-fields')
    while (el) { if (Number(getComputedStyle(el).opacity) < 1) return false; el = el.parentElement }
    return true
  })
  await base.locator('img').evaluate(async img => { await img.decode() })
  const left = await base.boundingBox(), right = await editor.boundingBox()
  assert.ok(left.x + left.width <= right.x && Math.abs(left.y - right.y) < 2)
  assert.match(await editor.innerText(), /每组最多 1 张/)
  assert.doesNotMatch(await editor.innerText(), /最多 20 张/)
  await page.screenshot({ path: path.join(output, 'revision-comparison-1280.png') })
  await base.locator('.hx-picture').getByRole('button').press('Enter')
  await page.locator('.el-image-viewer__wrapper').waitFor()
  await page.keyboard.press('Escape')
  assert.equal(await page.getByLabel('修改意见', { exact: true }).inputValue(), '意见须在原图放大后完整保留')
  await editor.locator('.el-upload input[type=file]').setInputFiles('public/demo-images/sample-1.jpg')
  await editor.getByText('模拟已接收', { exact: true }).waitFor()
  await editor.locator('.el-upload input[type=file]').setInputFiles('public/demo-images/sample-2.jpg')
  await editor.getByText('sample-2.jpg', { exact: true }).waitFor()
  await editor.getByText('模拟已接收', { exact: true }).waitFor()
  assert.equal(await editor.locator('.picture-card').count(), 1)
  checks.push('桌面原图与意见并排；点击放大关闭后意见保留；所有数量提示1张且上传第二张替换')
  await page.setViewportSize({ width: 640, height: 900 })
  const top = await base.boundingBox(), bottom = await editor.boundingBox()
  assert.ok(top.y + top.height <= bottom.y)
  await page.screenshot({ path: path.join(output, 'revision-comparison-640.png') })
  assert.equal(await page.getByLabel('修改意见', { exact: true }).inputValue(), '意见须在原图放大后完整保留')
  checks.push('640窄屏改为上下排列，意见及截图不丢失')
  await writeFile(path.join(output, 'template-revision-checks.json'), JSON.stringify({ status: 'PASS', checks }, null, 2))
  console.log(JSON.stringify({ status: 'PASS', checks }, null, 2))
} finally { await context.close(); await browser.close() }
