import assert from 'node:assert/strict'
import { writeFile } from 'node:fs/promises'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.DEMO_URL || 'http://127.0.0.1:3010/'
const browser = process.env.CDP_URL
  ? await chromium.connectOverCDP(process.env.CDP_URL)
  : await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) })
const context = await browser.newContext({ viewport: { width: 1280, height: 900 } })
const page = await context.newPage(), checks = []
page.setDefaultTimeout(15000)
try {
  let release
  const slow = new Promise(resolve => { release = resolve })
  await page.route('**/demo-images/sample-1.jpg', async route => { await slow; await route.continue() })
  await page.goto(`${base}?role=super_admin#/image-processing/wallpaper`, { waitUntil: 'domcontentloaded' })
  await page.getByText('图片加载中…', { exact: true }).first().waitFor()
  release()
  await page.waitForFunction(() => [...document.images].filter(i => i.getBoundingClientRect().width > 0).every(i => i.complete && i.naturalWidth > 0))
  await page.unroute('**/demo-images/sample-1.jpg')
  checks.push('慢图片显示加载态，加载完成后才显示缩略图')
  await page.route('**/demo-images/sample-1.jpg', route => route.abort())
  await page.reload({ waitUntil: 'domcontentloaded' })
  await page.locator('.hx-picture-state').filter({ hasText: '图片加载失败' }).first().waitFor()
  await page.unroute('**/demo-images/sample-1.jpg')
  await page.getByRole('button', { name: '重新加载', exact: true }).first().click()
  await page.waitForFunction(() => document.querySelector('.hx-selected-template img')?.naturalWidth > 0)
  checks.push('图片失败明确提示，重试成功恢复')
  const second = await context.newPage()
  second.setDefaultTimeout(15000)
  await second.goto(`${base}?role=super_admin#/tasks/index`)
  await second.getByText('此 Demo 场景已在另一标签页打开。请关闭那个页面，再刷新本页继续。', { exact: false }).first().waitFor()
  await second.getByRole('button', { name: '重置当前 Demo 场景' }).click()
  await second.getByRole('button', { name: '重置', exact: true }).click()
  await second.locator('.el-message--error').filter({ hasText: '此 Demo 场景已在另一标签页打开' }).waitFor()
  await second.close()
  checks.push('同场景第二标签页被阻止写入，避免本地数据互相覆盖')
  await page.getByRole('button', { name: '使用示例素材', exact: true }).click()
  await page.getByRole('textbox', { name: '任务名称', exact: true }).fill('保存失败不应出现的任务')
  await page.evaluate(() => { IDBObjectStore.prototype.put = function () { throw new DOMException('Injected quota', 'QuotaExceededError') } })
  await page.getByRole('button', { name: '提交生成任务', exact: true }).click()
  await page.getByText('Injected quota', { exact: false }).first().waitFor()
  assert.ok(!page.url().includes('?task='))
  await page.goto(`${base}?role=super_admin#/tasks/index`)
  await page.reload()
  await page.locator('.hx-page h1').waitFor()
  await page.getByText('秋日山川 · 手机屏幕系列', { exact: true }).waitFor()
  assert.equal(await page.getByText('保存失败不应出现的任务', { exact: true }).count(), 0)
  checks.push('存储写入失败不报成功、不跳任务详情，刷新恢复最后持久状态')
  await page.getByRole('button', { name: '重置当前 Demo 场景' }).click()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '重置当前 Demo 场景' }).click()
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await page.locator('.hx-page h1').waitFor()
  await page.getByText('秋日山川 · 手机屏幕系列', { exact: true }).waitFor()
  checks.push('重置确认可取消；确认后恢复初始数据')
  await page.evaluate(async () => {
    const db = await new Promise((resolve, reject) => { const r = indexedDB.open('hengxin-framework-demo-v1'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) })
    await new Promise((resolve, reject) => { const tx = db.transaction('states', 'readwrite'); tx.objectStore('states').put({ schema: 999 }, 'default:default'); tx.oncomplete = resolve; tx.onerror = reject })
    db.close()
  })
  await page.reload()
  await page.getByText('Demo 数据版本不兼容，请重置当前演示场景', { exact: false }).waitFor()
  await page.getByRole('button', { name: '重置当前 Demo 场景' }).click()
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await page.getByText('秋日山川 · 手机屏幕系列', { exact: true }).waitFor()
  checks.push('不兼容数据启动失败后可受锁保护重置；另一活动页数据不能被重置')
  await writeFile('../../output/framework-demo-2026-09-21/fault-results.json', JSON.stringify({ passed: true, checks }, null, 2))
  console.log(JSON.stringify({ passed: true, checks }, null, 2))
} catch (error) {
  console.error('URL', page.url(), (await page.locator('body').innerText()).slice(-5000)); throw error
} finally { await context.close(); await browser.close() }
