import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const base = process.env.DEMO_URL || 'http://127.0.0.1:3010/'
const output = path.resolve('../../output/framework-demo-2026-09-21')
await mkdir(output, { recursive: true })
const browser = process.env.CDP_URL
  ? await chromium.connectOverCDP(process.env.CDP_URL)
  : await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true })
const page = await context.newPage(), errors = [], apiRequests = [], checks = []
page.setDefaultTimeout(15000)
page.setDefaultNavigationTimeout(30000)
page.on('pageerror', error => errors.push(error.message))
page.on('request', request => { if (/^\/api(?:\/|$)/.test(new URL(request.url()).pathname)) apiRequests.push(request.url()) })
const go = async route => { await page.goto(`${base}?role=super_admin#${route}`); await page.locator('.hx-page h1').filter({ hasNotText: '恒鑫智图' }).waitFor() }
const screenshot = async name => {
  await page.locator('.hx-page h1').filter({ hasNotText: '恒鑫智图' }).waitFor()
  if (name.includes('wallpaper') || name.includes('templates')) await page.locator('.hx-page .hx-picture img').first().waitFor()
  await page.waitForFunction(() => [...document.querySelectorAll('.el-loading-mask')].every(e => !e.getBoundingClientRect().width || getComputedStyle(e).display === 'none'))
  await page.waitForFunction(() => [...document.images].filter(i => i.getBoundingClientRect().width > 0).every(i => i.complete && i.naturalWidth > 0))
  await page.waitForFunction(() => {
    let element = document.querySelector('.hx-page h1')
    while (element) { if (Number(getComputedStyle(element).opacity) < 1) return false; element = element.parentElement }
    return true
  })
  await page.screenshot({ path: path.join(output, `${name}.png`), fullPage: true, animations: 'disabled' })
}
const snapshot = () => page.evaluate(async () => {
  const db = await new Promise((resolve, reject) => { const r = indexedDB.open('hengxin-framework-demo-v1', 1); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) })
  const value = await new Promise((resolve, reject) => { const r = db.transaction('states').objectStore('states').get('default:default'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error) })
  db.close(); return value
})
try {
  await go('/image-processing/wallpaper')
  await screenshot('01-wallpaper-1440')
  await page.locator('.hx-selected-template .hx-picture').click()
  await page.keyboard.press('ArrowRight')
  await page.getByText('极简光影 · 手机屏幕套图 · 2 / 8', { exact: false }).waitFor()
  await screenshot('02-image-viewer')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('.el-image-viewer__wrapper').count(), 0)
  checks.push('模板图集鼠标打开、左右键切换、Esc 返回')
  await page.getByRole('button', { name: '更换模板', exact: true }).click()
  await page.locator('.hx-picture-mosaic .hx-picture').nth(2).click()
  await page.getByText('3 / 8', { exact: false }).waitFor()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '取消更换', exact: true }).click()
  await page.locator('.el-upload input[type=file]').setInputFiles(path.resolve('public/demo-images/sample-2.jpg'))
  await page.getByText('模拟已接收', { exact: true }).waitFor()
  await page.getByRole('textbox', { name: '任务名称', exact: true }).fill('框架闭环验收')
  await page.getByRole('button', { name: '提交生成任务', exact: true }).click()
  await page.locator('.hx-detail').waitFor()
  const taskUrl = page.url(), id = new URLSearchParams(taskUrl.split('?task=')[1] ? `task=${taskUrl.split('?task=')[1]}` : '').get('task')
  assert.ok(id)
  const before = await snapshot(), roundId = before.workspace.tasks.find(t => t.id === id).currentRoundId
  await page.reload()
  await page.locator('.hx-detail .hx-result-grid .hx-picture').first().waitFor()
  await page.getByRole('button', { name: '归档到成品库', exact: true }).waitFor()
  await page.waitForFunction(() => ![...document.querySelectorAll('button')].find(b => b.textContent.includes('归档到成品库'))?.disabled)
  const after = await snapshot()
  assert.equal(after.workspace.tasks.find(t => t.id === id).currentRoundId, roundId)
  assert.ok(after.workspace.tasks.find(t => t.id === id).sources[0].url.startsWith('data:image/jpeg'))
  checks.push('本地文件上传、任务生成、执行中刷新继续同一轮次、素材持久化')
  await screenshot('03-results-1440')
  await page.locator('.hx-detail .hx-result-grid .hx-picture').first().click()
  await page.keyboard.press('ArrowRight')
  await page.getByText('当前整套结果 · 2 / 8', { exact: false }).waitFor()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '修改这张', exact: true }).first().click()
  await page.getByLabel('修改意见', { exact: true }).fill('仅调整第一张的商品位置')
  await page.getByRole('button', { name: '提交修改', exact: true }).click()
  await page.waitForFunction(() => [...document.querySelectorAll('.hx-detail .el-select__selected-item')].some(e => e.textContent.includes('v2')))
  const revised = await snapshot(), slots = revised.slots.find(([key]) => key === id)[1]
  assert.deepEqual(slots.map(s => s.versions.length), [2,1,1,1,1,1,1,1])
  await page.getByRole('button', { name: '整套修改', exact: true }).click()
  await page.getByLabel('修改意见', { exact: true }).fill('统一整套明暗层次')
  await page.getByRole('button', { name: '提交修改', exact: true }).click()
  await page.waitForFunction(() => [...document.querySelectorAll('.hx-detail .el-select__selected-item')].some(e => e.textContent.includes('v3')))
  checks.push('单图返工仅增加目标版本，整套返工更新全组')
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载整套示例', exact: true }).click()
  const download = await downloadEvent
  assert.ok(download.suggestedFilename().endsWith('.zip'))
  assert.equal(await download.failure(), null)
  await page.getByRole('button', { name: '归档到成品库', exact: true }).click()
  await page.getByRole('button', { name: '查看该成品', exact: true }).click()
  await page.getByText('归档图片 · 后续修改不会覆盖此版本', { exact: true }).waitFor()
  await screenshot('04-archive-detail')
  await page.reload()
  await page.getByText('归档图片 · 后续修改不会覆盖此版本', { exact: true }).waitFor()
  checks.push('整套真实 ZIP 下载、归档快照、成品直达刷新')
  await go('/templates/index')
  await page.getByRole('button', { name: '新建模板', exact: true }).click()
  await page.getByPlaceholder('给这套模板起个容易找到的名字').fill('框架演示新模板')
  await page.getByRole('button', { name: '使用示例套图', exact: true }).click()
  await page.getByRole('button', { name: '保存模板', exact: true }).click()
  await page.getByRole('heading', { name: '框架演示新模板', exact: true }).waitFor()
  await page.reload()
  await page.getByRole('heading', { name: '框架演示新模板', exact: true }).waitFor()
  checks.push('模板新建保存与刷新持久化')
  await go('/management/settings')
  await page.getByRole('spinbutton', { name: '执行并发', exact: true }).fill('2')
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  await page.getByText('执行与上传 · 配置 v2', { exact: true }).waitFor()
  await page.reload()
  assert.equal(await page.getByRole('spinbutton', { name: '执行并发', exact: true }).inputValue(), '2')
  checks.push('配置保存、审计版本、刷新持久化')
  for (const [route, name] of [['/image-processing/product','05-product'], ['/image-processing/text','06-text'], ['/tasks/index','07-tasks'], ['/templates/index','08-templates'], ['/archive/index','09-archive'], ['/management/usage','10-usage'], ['/management/monitor','11-monitor'], ['/management/users','12-users'], ['/management/skills','13-skills'], ['/management/settings','14-settings']]) {
    await go(route); await screenshot(name)
  }
  await page.setViewportSize({ width: 1280, height: 900 })
  await go('/image-processing/wallpaper'); await screenshot('15-wallpaper-1280')
  await go('/templates/index'); await screenshot('16-templates-1280')
  await page.goto(`${base}?role=operator#/tasks/index`)
  await page.getByText('框架闭环验收', { exact: true }).waitFor()
  assert.equal(await page.getByRole('menuitem', { name: '系统配置', exact: true }).count(), 0)
  checks.push('所有业务及管理页面加载，1280/1440 截图、运营角色数据共用')
  await page.goto(`${base}?role=super_admin&scenario=empty#/tasks/index`)
  await page.getByText('暂无匹配任务', { exact: false }).waitFor()
  await screenshot('17-empty')
  await page.goto(`${base}?role=super_admin&scenario=partial-result#/image-processing/text`)
  await page.getByRole('button', { name: '使用示例素材', exact: true }).click()
  await page.getByRole('button', { name: '提交生成任务', exact: true }).click()
  await page.getByRole('button', { name: '重试失败范围', exact: true }).waitFor()
  await screenshot('18-partial-failure')
  await page.getByRole('button', { name: '重试失败范围', exact: true }).click()
  await page.waitForFunction(() => ![...document.querySelectorAll('button')].find(b => b.textContent.includes('归档到成品库'))?.disabled)
  checks.push('场景隔离、空态、部分失败保留结果与重试恢复')
  assert.deepEqual(errors, [])
  assert.deepEqual(apiRequests, [])
  checks.push('无浏览器运行异常；无真实 /api/ 请求')
  await writeFile(path.join(output, 'browser-results.json'), JSON.stringify({ passed: true, checks, errors, apiRequests }, null, 2))
  console.log(JSON.stringify({ passed: true, checks }, null, 2))
} catch (error) {
  await page.screenshot({ path: path.join(output, 'failure.png'), fullPage: true })
  console.error('URL', page.url(), '\n', (await page.locator('body').innerText()).slice(-7000))
  throw error
} finally { await context.close(); await browser.close() }
